### PR TITLE
Added logo, preview and updated readme

### PR DESCRIPTION
**Pull request by sedyh**
Hello, I've made a logo and preview page for dark and light modes.
I'm not sure if you will like, but I also applied the same color scheme to the badges.
I guess we can discuss the changes here.

image

### CODE REVIEW

**Comment by mcarpenter622** [comment]
I think this looks wonderful!  Only question is  should we put these images inside a folder? (including the root one?)  It seems strange that they are hanging out in the root.  Maybe a "Media" folder or something like that?

**Comment by sedyh** [comment]
Yeah, I can move it. Is "media" will be ok? Some people also names it docs or misc.

**Comment by sedyh** [comment]
I moved them.

**Comment by mcarpenter622** [comment]
Uhg, I just realized, this change breaks the newly merged GIF demo.  Could you please update the gif demo to be able to find the  _media/ebiten-ui.gif

**Comment by sedyh** [comment]
Ok, so I just need to sync the fork in order to get it updated I guess?

**Comment by sedyh** [comment]
Do you mean that line?
https://github.com/ebitenui/ebitenui/pull/188/files#diff-26bfcb22320efaccdac6394d2b7b616947638f2e71a7d732b19b95f5b72de127R74

**Review by mcarpenter622 — APPROVED** [review]

**Pull request merged**
