### PR TITLE
fix: set transparent color for NineSlice

### PR DESCRIPTION
**Pull request by ntsd**
- use the transparent color for the NineSlice when the color is nil

### CODE REVIEW

**Comment by mcarpenter622** [comment]
I'm ok with this change but why wouldn't you just use color.Transparent? Is there good use case for allowing nil ?

**Comment by ntsd** [comment]
> I'm ok with this change but why wouldn't you just use color.Transparent? Is there good use case for allowing nil ?

I think we can do a default NineSlice but that includes `*ebiten.Image` not sure what is a good default for these.

**Comment by mcarpenter622** [comment]
If you accept the cla I'll merge this pr.

**Review by mcarpenter622 — APPROVED** [review]

**Comment by mcarpenter622** [comment]
Thank you for the pr! I hope your enjoying the library. I'm always happy when others want to make this library better!

**Pull request merged**
