### PR TITLE
package: redesign package structure

### PR DESCRIPTION
**Pull request by gucio321**
- create examples folder
- remove extra go.mod

### CODE REVIEW

**Comment by mcarpenter622** [comment]
Hello! I reviewed the changes and there are a couple minor changes I would request before we merge this.

1. Please prepend the examples folder with an underscore  --  _examples
     This will prevent this folder from being built into the library. 

> [Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".](https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns)

2. Please update the .vscode/launch.json launch commands to point to the correct paths.

Thank you for your interest in helping grow ebitenui!
Mark

**Comment by mcarpenter622** [comment]
@gucio321 Any concerns with the requested updates above?

**Comment by gucio321** [comment]
oh, sorry, forgot about this, let me fix that

**Comment by gucio321** [comment]
@mcarpenter622 please check now

**Review by mcarpenter622 — APPROVED** [review]

**Comment by mcarpenter622** [comment]
Thank you for your PR!

**Pull request merged**
